export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const FETCH_EVENTS = "FETCH_POPULAR_ITEMS";
export const FETCH_EVENTS_START = "FETCH_POPULAR_ITEMS_START";
export const FETCH_EVENTS_SUCCESS = "FETCH_POPULAR_ITEMS_SUCCESS";
export const FETCH_EVENTS_FAIL = "FETCH_POPULAR_ITEMS_FAIL";
export const SET_UP_EVENTS = "SET_UP_POPULAR_ITEMS";

